var popup = document.createElement('div');
	popup.className = "popup";
var detail = document.createElement('div');
	detail.className = "detail"
var detail__close = document.createElement('img');
var detail__illustration = document.createElement('div');
var detail__img = document.createElement('img');
var detail__text = document.createElement('div');
var detail__price = document.createElement('p');
var detail__name = document.createElement('p');
var detail__author = document.createElement('p');
var detail__info_specialty = document.createElement('p');
var detail__year = document.createElement('p');
var detail__format = document.createElement('p');
var detail__size = document.createElement('p');
var detail__annotation = document.createElement('p');
var detail__reissue = document.createElement('p');